Dynamic datalink
django-daiquiri/daiquiri pull request #212
Opened 2023-09-01 14:13 UTC by agy-why

# This is the first attempt to create dynamic datalink.

## Why dynamic datalink?

making use of tables for datalink is useful since it allows more flexibility (for non-programmable entries) and it is easier to maintain.

Additionally the datalink entries are usually part of the release, and as such get a DOI. 

However, in one cases making use of tables to provide datalink entries may not be confortable:
* in case of too many entries: like in Gaia, several datalink entries per source_id (same for applause...)

In these cases datalink entries generated on the fly based on the ID are necessary.

## Implementation

I added a DynamicDatalinkAdapterMixin class that take care of the dynamic datalink entries. I also added a method called: `get_datalink_rows` and `get_dyn_datalink_links` to the `BaseDatalinkAdapter`, to provide a single point of gathering for the datalink entries (slighlty slower). 

This improve greatly the maintenance and flexibility.

These changes should not break the former functionality.

## How to

With this new implementation it is possible to add new datalink entries by overwriting the method:

`get_dyn_datalink_links` from the DatalinkAdapter. This method returns a list of dynamic datalink entries for the provided IDs. The user is free of implementing anything necessary. It just need to declare the new DatalinkAdapter in `settings/base.py`

## Improvements

This pull request also solves some issues the previous implementation had:
1. There were various place in the code where the datalink data were gathered, making maintenance difficult
2. There were no flexibility in the way OAI and Datalink were connected (now there is an adapter).

2023-09-01 14:14 UTC, agy-why commented
This is working with the dynamic-datalink branch of gaia-app

2023-09-04 14:49 UTC, agy-why commented on daiquiri/datalink/adapter.py
> +        dyn_rows = [tuple(link.values()) for link in self.get_dyn_datalink_links(identifiers)]
`tuple(link.values())` does not guaranty the order of the items in the resulting array.

2023-09-22 07:13 UTC, kimakan commented on daiquiri/oai/adapter.py
> +        rows = adapter.get_datalink_rows([pk])
At this point `pk` is not defined yet.

2023-09-22 13:29 UTC, kimakan requested changes
The current implementation breaks `rebuild_oai_schema`. The culprit is the re-implemented `get_datalink_list` which is used by `rebuild_oai_schema`. In general, this function must return __all__ datalink entries with the semantic `#doi`. This must be addressed.

2023-09-29 14:05 UTC, kimakan approved these changes

2023-09-29 14:05 UTC, merged